### ISSUE TITLE
Unnecessary function

### ISSUE THREAD

**Issue by Eruptsy** [dropout1337/TikTok-Username-Checker#1]
unnecessary function. ANSI can be used for both Linux and Windows OS(s). So an OS check is not needed

https://github.com/dropout1337/TikTok-Username-Checker/blob/384ce28bd79d78ec9c12c3961855a40eadab746d/main.go#L143

**Comment by dropout1337** [comment]
im dead x2, called making readable code and not fucking "\x1b[autism"

**Comment by Eruptsy** [comment]
That isnt the way i was referring to when i said ANSI either. Thats also a nooby practice. This happens when you assume. When you don’t know much, you’re limited to doing/creating things.
