### ISSUE TITLE
Unnecessary code

### ISSUE THREAD

**Issue by Eruptsy** [dropout1337/TikTok-Username-Checker#2]
Empty Println() function used to output a newline is pointless. Also, using a bunch of println() function back to back is useless. Use a variable to set the format of string and just output it. 

https://github.com/dropout1337/TikTok-Username-Checker/blob/384ce28bd79d78ec9c12c3961855a40eadab746d/main.go#L84

**Comment by dropout1337** [comment]
🥼 im dead. its called making the ui look good.

**Comment by Eruptsy** [comment]
If you need help positioning UIs. Lmk
